#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "dec_func.c"
#include "dec_data.c"


int ve;
int ve2;
struct listadeint lx;
struct listadeint lx2;
int main(){
struct listadeint tmp_4= listadeint_default;
insertarint(&tmp_4,1);
insertarint(&tmp_4,2);
insertarint(&tmp_4,3);
insertarint(&tmp_4,4);
lx=tmp_4;
struct listadeint tmp_5= listadeint_default;
insertarint(&tmp_5,5);
insertarint(&tmp_5,6);
lx2=tmp_5;
int tmp_6;
tmp_6 = getLongitudListaint(lx);
printf("%s%d%s","Longitud: ", tmp_6, " \n");
int tmp_7;
tmp_7 = imprimirlista(lx);
ve=tmp_7;
int tmp_8;
tmp_8 = getActualListaint(lx);
printf("%s%d%s","Elemento Actual: ", tmp_8, " \n");
avanzarListaint(&lx);
int tmp_9;
tmp_9 = getActualListaint(lx);
printf("%s%d%s","Elemento Actual: ", tmp_9, " \n");
retrocederListaint(&lx);
int tmp_10;
tmp_10 = getActualListaint(lx);
printf("%s%d%s","Elemento Actual: ", tmp_10, " \n");
int tmp_11;
tmp_11 = getElementoint(lx,3);
printf("%s%d%s","Elemento Posicion 3: ", tmp_11, " \n");
irAPosicionint(&lx,0);
printf("%s","Borrando lista por la mitad \n");
struct listadeint tmp_12;
tmp_12 = borrarListaint(lx,2);
lx=tmp_12;
int tmp_13;
tmp_13 = imprimirlista(lx);
ve=tmp_13;
int tmp_14;
tmp_14 = getLongitudListaint(lx);
printf("%s%d%s","Elemento Longitud nueva: ", tmp_14, " \n");
printf("%s","Concatenando listas...\n");
struct listadeint tmp_15;
tmp_15 = concatenerListas(lx,lx2);
lx=tmp_15;
int tmp_16;
tmp_16 = getLongitudListaint(lx);
printf("%s%d%s","Elemento Longitud Lx nueva: ", tmp_16, " \n");
int tmp_17;
tmp_17 = imprimirlista(lx);
ve=tmp_17;
printf("%s%s","Quitando elemento posición 1", "\n");
struct listadeint tmp_18;
tmp_18 = removeElementint(lx,1);
lx=tmp_18;
int tmp_19;
tmp_19 = imprimirlista(lx);
ve=tmp_19;
printf("%s%s","Añadiendo 1 en la posición 2", "\n");
struct listadeint tmp_20;
tmp_20 = addElementAtint(lx,2,1);
lx=tmp_20;
int tmp_21;
tmp_21 = imprimirlista(lx);
ve=tmp_21;
printf("%s%s","Sumar 1 a la lista", "\n");
struct listadeint tmp_22;
tmp_22 = IntOperationListaint(lx,1,1);
lx=tmp_22;
int tmp_23;
tmp_23 = imprimirlista(lx);
ve=tmp_23;
printf("%s%s","Restar 1 a la lista", "\n");
struct listadeint tmp_24;
tmp_24 = IntOperationListaint(lx,1,0);
lx=tmp_24;
int tmp_25;
tmp_25 = imprimirlista(lx);
ve=tmp_25;
printf("%s%s","Multiplicar 2 a la lista", "\n");
struct listadeint tmp_26;
tmp_26 = IntOperationListaint(lx,2,2);
lx=tmp_26;
int tmp_27;
tmp_27 = imprimirlista(lx);
ve=tmp_27;
printf("%s%s","Dividir 2 a la lista", "\n");
struct listadeint tmp_28;
tmp_28 = IntOperationListaint(lx,2,3);
lx=tmp_28;
int tmp_29;
tmp_29 = imprimirlista(lx);
ve=tmp_29;
int tmp_30;
tmp_30 = getIntFromlistaint(lx,1,1);
ve=tmp_30;
printf("%d%s",ve, "\t");
int tmp_31;
tmp_31 = getIntFromlistaint(lx,1,0);
ve=tmp_31;
printf("%d%s",ve, "\t");
int tmp_32;
tmp_32 = getIntFromlistaint(lx,1,2);
ve=tmp_32;
printf("%d%s",ve, "\t");
int tmp_33;
tmp_33 = getIntFromlistaint(lx,1,3);
ve=tmp_33;
printf("%d%s",ve, "\t\n");

}